spring:
  application:
    name: spring-ai-mcp-client
  profiles:
    active: test
  ai:
    mcp:
      client:
        enabled: true
        name: spring-ai-mcp-client
        type: ASYNC

        sse:
          connections:
            server1:
              url: https://mcp.amap.com
              sse-endpoint: /sse?key=e7d1387f68227d3d03cbb94621ce1c4f
              connect-timeout: 120s
              read-timeout: 120s
            server2:
              url: http://localhost:9060
              sse-endpoint: /sse
              connect-timeout: 180s
              read-timeout: 180s
        stdio:
          connect-timeout: 180s
          read-timeout: 180s
          servers-configuration: classpath:mcp-server.json

        request-timeout: 180s
    vectorstore:
      redis:
        initialize-schema: true #是否初始化所需的模式
        index-name: wjh-vectorstore # 用于存储向量的索引名称
        prefix: 'embedding:'   # Redis的前缀
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: ${OPENAI_BASE_URL}
      chat:
        options:
          model: ${OPENAI_MODEL}
  data:
    redis:
      host: 127.0.0.1
      port: 9379
      password: 123456
logging:
  level:
    root: info

internet:
  webSearch:
    searxng:
      url: http://localhost:6080/search
      counts: 5